version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ssagalov/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static_back/
      - media_value:/app/media/
      - redoc_value:/app/api/docs/
    depends_on:
      - frontend
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_back/
      - media_value:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web

volumes:
  db_data:
  static_value:
  media_value:
  redoc_value:
