# Generated by Django 2.2.19 on 2023-05-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['id'], 'verbose_name': 'Мои подписки', 'verbose_name_plural': 'Мои подписки'},
        ),
    ]
